---
- hosts: master
  become: yes
  tasks:
    - name: initialize the cluster
      shell: | 
        kubeadm init \
          --pod-network-cidr=10.244.0.0/16 \
          --kubernetes-version=v1.19.3 \
          --apiserver-cert-extra-sans=brassberry.dixneuf19.me \
          >> cluster_initialized.txt
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

    - name: create .kube directory
      become: yes
      become_user: ubuntu
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        remote_src: yes
        owner: ubuntu

    - name: Install Flannel
      become: yes
      become_user: ubuntu
      command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

    - name: Untaint master
      become: yes
      become_user: ubuntu
      command: kubectl taint nodes --all node-role.kubernetes.io/master-
      register: command_result
      failed_when: 
        - '"taint \"node-role.kubernetes.io/master\" not found" not in command_result.stderr'
        - result.rc != 0
